### ISSUE TITLE
Median frame mode

### ISSUE THREAD

**Issue by bale-go** [wq2012/video-average-frame#1]
I found your script really useful to create less noisy images from my night camera stream.
I decided to add a feature to process the frames by using the median instead of the average.
The median is a robust measure of central tendency. In average every frame is used, resulting in blurry images if something moves quickly in the video stream (e.g. seagull flying, buoy moving in the background). 
Median uses the most typical value of the given pixel, providing a sharper image.
![--mode=median](https://user-images.githubusercontent.com/66311383/119483154-f7f71600-bd54-11eb-89ea-6df5985c5459.jpg)

If you are interested, I can do a PR.

**Comment by wq2012** [comment]
Yeah, I agree with everything you said.

Just that medium can be computationally expensive if the video is long, since you need to keep all values in memory.

Feel free to send PR if you wish to.

**Comment by bale-go** [comment]
Yes, that is why I opted to use the median of the median of 50 frames. 
It reduced the memory impact significantly.
