### ISSUE TITLE
Reduce memory consumption

### ISSUE THREAD

**Issue by cmahnke** [wq2012/video-average-frame#7]
Currently it seems that the program loads everything into memory. Given a video with more then a few 10000 frames this eats up several gigs of RAM. It might be a solution to clear processed frames from memory...

**Comment by wq2012** [comment]
Feel free to send a pull request :wink:

**Comment by cmahnke** [comment]
Well, it seems to be related to the mode, it seems to be only (as in noticeable) in `--mode median`. I don't know the code good enough to propose a fix.

**Comment by wq2012** [comment]
Ah you are right. The issue only happens for median mode.

Average/max/min does not need to memorize all past frames. But median mode does need that.

There could be some proximate moving median algorithms (not a trivial algorithm) out there. I will take a look.

**Comment by cmahnke** [comment]
Well, I'm not sure you really need *all* frames, since I would suspect duplicate frames/ pixels (even there might be additional noise due to video compression artifacts), it should be possible to do so sort of 4D run length encoding. That is just counting repeated pixels at a given position, since the order itself shouldn't matter.

For me it isn't urgent anymore I make my own script and metioned this tool [here](https://christianmahnke.de/en/post/pong/).

**Comment by wq2012** [comment]
I see. You are right! Pixel values are discrete so just need to maintain a histogram in cache. No need for caching all frames.

Since it's not urgent needed, I will mark it closed.
